#!/bin/bash

folder_Custom_Commands="$HOME/.customCommands"

scriptdot="dot"

rm -rf "$folder_Custom_Commands/commands"

mkdir "$folder_Custom_Commands/commands"

cp -R "$DOTFILES_PATH/commands" "$folder_Custom_Commands"
rm -rf "$folder_Custom_Commands/commands/dot"

cd "$folder_Custom_Commands"

git pull origin "$(git rev-parse --abbrev-ref HEAD)"
git add .
git commit -m 'Update Commands'
git push origin HEAD