#!/bin/bash

repository="${1}"

folder_Custom_Commands="$HOME/.commands-$repository"

scriptdot="dot"

rm -rf "$folder_Custom_Commands/commands"
mkdir "$folder_Custom_Commands/commands"
if [ -d "$folder_Custom_Commands/commands" ]; then
    if [ -d "$DOTFILES_PATH/commands_custom/$repository/commands" ]; then
        cp -R "$DOTFILES_PATH/commands_custom/$repository/commands" "$folder_Custom_Commands"
    fi
fi

cd "$folder_Custom_Commands"

git pull origin "$(git rev-parse --abbrev-ref HEAD)"
git add .
git commit -m 'Update Commands'
git push origin HEAD