#!/bin/bash

repository="${1}"

folder_Custom_Commands="$HOME/.commands-$repository"

scriptdot="dot"

rm -rf "$folder_Custom_Commands/commands"

mkdir "$folder_Custom_Commands/commands"

cp -R "$DOTFILES_PATH/commands_custom/$repository/commands" "$folder_Custom_Commands"
#cp -R "$DOTFILES_PATH/git" "$folder_Custom_Commands"

cd "$folder_Custom_Commands"

git pull origin "$(git rev-parse --abbrev-ref HEAD)"
git add .
git commit -m 'Update Commands'
git push origin HEAD