#!/bin/bash

module="${1}"
command="${2}"

mkdir "${DOTFILES_PATH}/scripts/$module"
mkdir "${DOTFILES_PATH}/docs/$module"

echo "#!/bin/bash" > "${DOTFILES_PATH}/scripts/$module/$command"
echo "" >> "${DOTFILES_PATH}/scripts/$module/$command"
echo "echo \"New command created\"" >> "${DOTFILES_PATH}/scripts/$module/$command"

echo "#!/bin/bash" > "${DOTFILES_PATH}/docs/$module/$command"
echo "" >> "${DOTFILES_PATH}/docs/$module/$command"
echo "echo \"$module\"" >> "${DOTFILES_PATH}/docs/$module/$command"
echo "echo \"\"" >> "${DOTFILES_PATH}/docs/$module/$command"
echo "echo \"Description:\"" >> "${DOTFILES_PATH}/docs/$module/$command"
echo "echo \"$command\"" >> "${DOTFILES_PATH}/docs/$module/$command"
echo "echo \"\"" >> "${DOTFILES_PATH}/docs/$module/$command"
echo "echo \"\"" >> "${DOTFILES_PATH}/docs/$module/$command"
echo "echo \"\"" >> "${DOTFILES_PATH}/docs/$module/$command"
echo "echo \"Params:\"" >> "${DOTFILES_PATH}/docs/$module/$command"
echo "echo \"- Param 1\"" >> "${DOTFILES_PATH}/docs/$module/$command"

chmod -R 777 $HOME/.dotfiles/scripts
chmod -R 777 $HOME/.dotfiles/docs