#!/bin/bash

repoGit=${1}
branch=${2}
override=${3}
folderCustomCommands=$HOME/.customCommands

if [ -d "$folderCustomCommands" ]; then
    rm -rf $folderCustomCommands
fi

git clone $repoGit $folderCustomCommands
cd $folderCustomCommands

git checkout $branch

paths=$(ls $DOTFILES_PATH/scripts)
scriptdot="dot"

for folder in ${paths}; do
    if [ $folder != $scriptdot ]; then
	if [[ $override == "true" ]]; then
	    rm -rf $DOTFILES_PATH/scripts/$folder
	    rm -rf $DOTFILES_PATH/docs/$folder
	fi
    fi
done

if [ -d scripts ]; then
    cp -R scripts $DOTFILES_PATH
    cp -R docs $DOTFILES_PATH
fi
