#!/bin/bash

module="${1}"
command="${2}"

if [ -d "${DOTFILES_PATH}/scripts/$module" ];
then
    if [ -f "${DOTFILES_PATH}/scripts/$module/$command" ];
    then
        rm "${DOTFILES_PATH}/scripts/$module/$command"
        rm "${DOTFILES_PATH}/docs/$module/$command"
        echo "Command removed succesful!!"
    else
        echo "Command not exist!!"
    fi
else
    echo "Module not exist!!"
fi