#!/bin/bash

module="${1}"

if [ -d "${DOTFILES_PATH}/scripts/$module" ];
then
    rm -r "${DOTFILES_PATH}/scripts/$module"
    rm -r "${DOTFILES_PATH}/docs/$module"
    echo "Module removed succesful!!"
else
    echo "Module not exist!!"
fi