#!/bin/bash

repository="${1}"

echo "Updating Commands"

folder_Custom_Commands="/home/jchavez/.commands-$repository"
cd "$folder_Custom_Commands"

git pull origin "$(git rev-parse --abbrev-ref HEAD)"

if [ -d "$folder_Custom_Commands/commands" ]; then
    cp -R "$folder_Custom_Commands/commands" "$DOTFILES_PATH/commands_custom/$repository"
fi

if [ -d "$folder_Custom_Commands/ssh" ]; then
    cp -R "$folder_Custom_Commands/ssh" "$DOTFILES_PATH"
fi

if [ -d "$folder_Custom_Commands/dependencies" ]; then
    cp -R "$folder_Custom_Commands/dependencies" "$DOTFILES_PATH"
fi