- defaults:
    sync:
      rsync: 'rsync'                        # rsync executable to be used
      options: ['--delete', '--safe-links'] # list of options for rsync
      create: false                         # create missing directory hierarchy
      fmode: 644                            # file mode
      dmode: 755                            # directory mode
      owner: 'root'          # owner (default value is looked up at runtime)
      group: 'root'         # group (default value is looked up at runtime)
      stdout: false                         # ignore stdout of rsync process
      stderr: false                         # ignore stderr of rsync process

- sync:
    /mnt/c/workspace:
       path: '~/workspace'
       fmode: 400