#!/bin/bash

echo "vim"
echo ""
echo "Description:"
echo "Exit Vim"
echo ""
echo ":w  -> write (save) the file, but don't exit"
echo ":wq -> write (save) and quit"
echo ":q  -> quit (fails if there are unsaved changes)"
echo ":q!  -> quit and throw away unsaved changes"
