#!/bin/bash

echo "vim"
echo ""
echo "Description:"
echo "Insert text"
echo ""
echo "i -> insert before the cursor"
echo "I -> insert at the beginning of the line"
echo "a -> insert (append) after the cursor"
echo "A -> insert (append) at the end of the line"
