#!/bin/bash

echo "Updating dot"

cd "$DOTFILES_PATH"

git pull origin master

chmod -R 777 "$DOTFILES_PATH/commands"

"$HOME/.local/bin/dotbot" -c "$DOTFILES_PATH/configs/symlinks.yaml" -d "$DOTFILES_PATH"