#!/bin/bash

echo "Updating dot"

cd "$DOTFILES_PATH"

git pull origin master

chmod -R 777 "$DOTFILES_PATH/commands"

"$HOME/.local/bin/dotbot" -c "$DOTFILES_PATH/configs/symlinks.yaml" -d "$DOTFILES_PATH"

cd "$DOTFILES_PATH"

for file in $(git status --porcelain | cut -c4-); do
    if [ ! "$file" == "git/.gitconfig" ]; then
        if [ ! "$file" == "git/.gitignore_global" ]; then
            git add "$file"
        fi
    fi
done

git commit -m 'Update Commands'
git push origin HEAD