#!/bin/bash

repoGit=${1}
branch=${2}
alias=${3}
folder_Custom_Commands="$HOME/.commands-$alias"

if [ -d "$folder_Custom_Commands" ]; then
    rm -rf "$folder_Custom_Commands"
fi

git clone $repoGit "$folder_Custom_Commands"
cd "$folder_Custom_Commands"

git checkout "$branch"

rm -rf "$DOTFILES_PATH/commands_custom/$alias"

if [ -d "$folder_Custom_Commands/commands" ]; then
    mkdir "$DOTFILES_PATH/commands_custom/$alias"
    cp -R "$folder_Custom_Commands/commands/." "$DOTFILES_PATH/commands_custom/$alias"
    rm -rf "$folder_Custom_Commands/commands/dot"
else
    mkdir "$DOTFILES_PATH/commands_custom/$alias"
fi

if [ -d "$folder_Custom_Commands/git" ]; then
    echo "Setup git configuration"
    echo -ne '#####                     (33%)\r'
    sleep 1
    echo -ne '#############             (66%)\r'
    sleep 1
    

    ls -A "$folder_Custom_Commands/git" | xargs -I _ sh -c 'cp "$HOME/.commands-public/git/_" $HOME/.commands-ship/git'

    echo -ne '#######################   (100%)\r'
    echo -ne '\n'
fi

if [ -d "$folder_Custom_Commands/ssh" ]; then
    cp -R "$folder_Custom_Commands/ssh" "$DOTFILES_PATH"
    ls $folder_Custom_Commands/ssh | xargs -I _ sh -c 'echo "ssh-add ~/.ssh/_" >> ~/.commands-ship/shell/init.sh'
    ls $folder_Custom_Commands/ssh | xargs -I _ sh -c 'chmod 600 ~/.ssh/_'
fi

if [ -d "$folder_Custom_Commands/dependencies" ]; then
    cp -R "$folder_Custom_Commands/dependencies" "$DOTFILES_PATH"
fi
