#!/bin/bash

repoGit=${1}
branch=${2}
alias=${3}
folder_Custom_Commands="$HOME/.customCommands-$alias"

if [ -d "$folder_Custom_Commands" ]; then
    rm -rf "$folder_Custom_Commands"
fi

git clone $repoGit "$folder_Custom_Commands"
cd "$folder_Custom_Commands"

git checkout "$branch"

rm -rf "$DOTFILES_PATH/commands_custom/$alias"

if [ -d "$folder_Custom_Commands" ]; then
    mkdir "$DOTFILES_PATH/commands_custom/$alias"
    cp -R "$folder_Custom_Commands/commands" "$DOTFILES_PATH/commands_custom/$alias"
    cp -R "$folder_Custom_Commands/git" "$DOTFILES_PATH"
    rm -rf "$folder_Custom_Commands/commands/dot"
fi
